### ISSUE TITLE
Cannot change trip disp position and batt consumed position

### ISSUE THREAD

**Issue by roque-canales** [PlayUAV/PlayuavOSD#14]
V1.0.0.8 and latest firmware:

We can change but if reboot after power lost, trip dist is reset to default position

Idem for battery consumed.

Could you please check?

**Comment by ghost** [comment]
Hi, the "battery consumed" and "traveled distance" is calculated(simulation) by OSD firmware. If you reset the OSD,  the value will return to the initialization(zero), even with the power on.

**Comment by roque-canales** [comment]
I don't want to mean that, It talk about to be able to set it's position like the others items.

We can change it like the other, but when reboot, other items stay where we set while total trip dist item and battery consumed item replace at the standard setup.

**Comment by ghost** [comment]
The new firmware does have this issue! 
I have fixed it. https://github.com/PlayUAV/PlayuavOSD/commit/9744440c05f13dc1115b657993300d239727c3a8
Please update the firmware with CT.

**Comment by roque-canales** [comment]
perfect,

This work now !

Thanks lot Rentt.
