### ISSUE TITLE
cannot save parameters on hard drive with GUI on Win8.1 64bit

### ISSUE THREAD

**Issue by roque-canales** [PlayUAV/PlayuavOSD#15]

**Comment by ghost** [comment]
How about firmware update, parameter reading and saving parameters to memory?  Can they work all right? Is this question related to issue #14? If so, I will have #15 closed.

**Comment by roque-canales** [comment]
No this issue is relating the GUI.

When we want to save params on hard drive using menu file OSD file, we enter file name and click on save button, and at this moment we have software error:

---

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at OSD.PlayuavOSD.saveOSDFileToolStripMenuItem_Click(Object sender, EventArgs e) in E:\project\Playuav\OSDTool\playuavosd.cs:line 1815
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34014 built by: FX45W81RTMGDR

##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

OSD_Config
    Assembly Version: 2.1.3.0
    Win32 Version: 1.0.0.0

##     CodeBase: file:///C:/Users/user/Downloads/OSDTool(6)/OSD_Config.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

log4net
    Assembly Version: 1.2.11.0
    Win32 Version: 1.2.11.0

##     CodeBase: file:///C:/Users/user/Downloads/OSDTool(6)/log4net.DLL

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

ObjectListView
    Assembly Version: 2.5.1.30870
    Win32 Version: 2.5.1.0

##     CodeBase: file:///C:/Users/user/Downloads/OSDTool(6)/ObjectListView.DLL

OpenTK.GLControl
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1536.5788

##     CodeBase: file:///C:/Users/user/Downloads/OSDTool(6)/OpenTK.GLControl.DLL

OpenTK
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1536.5788

##     CodeBase: file:///C:/Users/user/Downloads/OSDTool(6)/OpenTK.DLL

System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll

BouncyCastle.Crypto
    Assembly Version: 1.7.4137.9283
    Win32 Version: 1.7.4137.9283

##     CodeBase: file:///C:/Users/user/Downloads/OSDTool(6)/BouncyCastle.Crypto.DLL

Ionic.Zip
    Assembly Version: 1.9.2.0
    Win32 Version: 1.9.2

##     CodeBase: file:///C:/Users/user/Downloads/OSDTool(6)/Ionic.Zip.DLL

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.0.30319.34014 built by: FX45W81RTMGDR

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll

System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34212 built by: FX452RTMGDR

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ghost** [comment]
When I tried to save and load the parameters to file, the save action was successful but the load didn't work. I then found out that the problem was caused by the attitude_X_scale parameters. I have fixed it and here is the new build. Would you like to test it?
http://www.playuav.com/download/playuavosd/Debug.zip

**Comment by roque-canales** [comment]
hello,

This no work, now we cannot star the GUI.

When we launch it popup "bad parameter of Attitude_MP_Scale_Real" appears, and Popup "OSD has stopped working" appears....

**Comment by ghost** [comment]
Hi,

The error "bad parameter of Attitude_MP_Scale_Real" is caused by region settings of Windows. See http://en.playuav.com/question/7

The fix version has been released and the CT should update automatically.

**Comment by ghost** [comment]
Hi,
Does it still happen with the latest Config Tool?

**Comment by roque-canales** [comment]
No now it's perfect your fix work
