### ISSUE TITLE
Add channel 9 - 16 for switch video and switch pannel

### ISSUE THREAD

**Issue by roque-canales** [PlayUAV/PlayuavOSD#16]
Hello,

I'm using arducopter AC3.3 with pixhawk  and 16ch sbus receiver, and Copter 3.3 firmware enable 16 channels.
Could you please update firmware to enable 9-16ch ?

Kind regards.

**Comment by ghost** [comment]
There is a MAVLINK message(MAVLINK_MSG_ID_RC_CHANNELS) which contains 18 channels value. Will check if it works with OSD.

**Comment by roque-canales** [comment]
Hello rent, I check your code, and you handle only 8 channels, please update it quickly we absolutely need to be able to use channel 15 and 16 please.

**Comment by roque-canales** [comment]
we are able to test your update ASAP

**Comment by ghost** [comment]
Hi,
I have built a testing firmware and tested with my T8FG using ch9 and ch10 as switch channel. Please update the custom firmware and set the switch channel at CT. 
http://www.playuav.com/download/playuavosd/prerelease/PlayuavOSD_ch16.hex

FYI, there is no checking about Config Tool, it means you can input any value from 1 to 16. It is a bug and should add verify codes:-)

**Comment by roque-canales** [comment]
Perfect Rentt!!!

So now it work for switch camera on channel 15 an 16.

But no work for panel change, could you please add same thing for panel switch?

Like this all will be perfect!

**Comment by ghost** [comment]
I have added the same codes for panel switching. Now you can update the firmware with the CT(also should be updated). Looking forward your testing.

**Comment by roque-canales** [comment]
I think you forgot something... panel switching still no work...

**Comment by roque-canales** [comment]
It's working...

Pefect, Panel switching is ok from ch 9- 16.

**Comment by efeksk** [comment]
> Merhaba,
> bir test ürün yazılımı oluşturdum ve anahtar kanalı olarak ch9 ve ch10 kullanarak T8FG ile test ettim. Lütfen özel ürün yazılımını güncelleyin ve anahtar kanalını CT olarak ayarlayın.
> http://www.playuav.com/download/playuavosd/prerelease/PlayuavOSD_ch16.hex
> 
> FYI, Yapılandırma Aracı ile ilgili bir kontrol yok, 1'den 16'ya kadar herhangi bir değer girebileceğiniz anlamına gelir. Bu bir hata ve doğrulama kodları eklemeniz gerekir :-)


Hello there
I cannot access this file.
I ask you to reload
