### ISSUE TITLE
Armed state timer reset error

### ISSUE THREAD

**Issue by roque-canales** [PlayUAV/PlayuavOSD#18]
Timer reset each time we disarm drone, could you please remove reset of timer each time we disarm?

Idea is to watch total time in the air so in armed state with the same lipo....

**Comment by ghost** [comment]
There are three options for timer. You can set the "Time_Type" with CT.
0: counting from power on
1: counting from last MAVLINK heartbeat
2: counting from armed

**Comment by roque-canales** [comment]
Ok, but I want total armed time with one battery.

So I can arm, fly and disarm, then refly and disarm.

And now is reseting timer each time we disarm...

When disarmed timer is paused, and when re arm timer re star count.

You can make that? I think is just remove reset when drone is disarm, but just pause count.

**Comment by ghost** [comment]
Got it. Just make a test firmware. Please try it.
http://www.playuav.com/download/playuavosd/prerelease/PlayuavOSD_armedtime.hex

BTW, there are some issues reported by you. If the issue be fixed, please let me know so I can close them. Or you can close them by yourself. Thank you.

**Comment by roque-canales** [comment]
GJob, perfect, you got it! Thanks
