### ISSUE TITLE
OSDTool not showing screen layout

### ISSUE THREAD

**Issue by i--storm** [PlayUAV/PlayuavOSD#2]
![2015-06-24 15-38-18 playuavosd-v1 0 0 6](https://cloud.githubusercontent.com/assets/5264147/8330034/1ae9b946-1a87-11e5-939a-b51a3ba788ea.png)

**Comment by i--storm** [comment]
Found the decision:
In regional settings it should be dot as decimal separator.

**Comment by ghost** [comment]
Great! Closed.
