### ISSUE TITLE
Webpage in English

### ISSUE THREAD

**Issue by SamuelBrucksch** [PlayUAV/PlayuavOSD#3]
Hi,

just saw this project and its pretty amazing. I want to help as i want to use this OSD to send telemetry over video (VBI) for my antenna tracker project (open360tracker here on github). But your webpage is chinese only, so i cannot contribute to it as i do not understand anything.

Also is there a way to contact you directly?

Regards

Samuel

**Comment by ghost** [comment]
Hi Samuel,

Thank you for your interest in the project. It will be great if we can have international developers join the program and help it to grow. We will soon build the English webpage. I will keep you updated on the progress. Meanwhile, you can write to me directly and we can exchange ideas. My email address is: rentt@playuav.com

Best regards,
Tom

**Comment by SamuelBrucksch** [comment]
Can be closed.
