### ISSUE TITLE
Enhancement request/Bugfix: delayed startup

### ISSUE THREAD

**Issue by athertop** [PlayUAV/PlayuavOSD#31]
I often find that when the craft is first powered up for flight, the PlayUAV momentarily flickers the camera output on the OSD screen (without telem overlay) then simply displays a blank screen with no camera output or telemetry overlay from that point on. The only way I can imagine the cause of this would be if the PlayUAV started up before the telemetry feed from the Pixhawk and decided that no telem feed = choose not to startup. Re-powering the craft often cures this race condition (assuming this is in fact the cause) and things then work normally. This is of course a guess as to the cause, but if this suggestion was in fact true, then would it be possible to introduce a delayed startup on the PlayUAV OSD, such that it allows the Pixhawk to boot up before the OSD checks for the telemetry feed? Maybe a manually entered delay parameter in the settings? If this assessment is not true, then maybe some other bug causing the startup failure. Not sure if I am able to capture a log in some way to help with debugging of this issue, but would be happy to assist where possible to find a resolution. Thanks.

**Comment by TobiasBales** [comment]
The osd works fine without telemetry actually,
it could be that your camera initially takes too long to initialize initially and that might cause issues,
but I am not certain.

Is it possible to power your camera before powering the rest?
The would be a nice starting point to debug the issue.

**Comment by TobiasBales** [comment]
@athertop The osd does work fine when the mav link data comes somewhat later (it does take a while for me) the issues is probably something else.
Have you tried hitting the reset button on the osd after startup to see if the picture is there then?

**Comment by TobiasBales** [comment]
@athertop did this fix itself? Or did you change something?
Just so we have that documented ;)

**Comment by athertop** [comment]
I think it might have been due to having 2 cameras one pal and the other ntsc. Seems OK now
