### ISSUE TITLE
Please share compiled latest config tool for windows

### ISSUE THREAD

**Issue by roque-canales** [PlayUAV/PlayuavOSD#7]

**Comment by rentt** [comment]
Add a wiki page for building on windows:
http://www.playuav.com/wiki/doku.php?id=playuavosd:dev:windows_build

**Comment by ghost** [comment]
http://www.playuav.com/download/playuavosd/OSDTool.zip

**Comment by roque-canales** [comment]
I cannot install it...... i have windows8.1.  Could you explain install process for osdtool.zip please?

**Comment by ghost** [comment]
I have not tested it on windows8.1. I will test it later. Below is the instruction. If there are still errors, please let me know.
http://www.playuav.com/wiki/doku.php?id=projects:playuavosd:instruction

**Comment by damienyong** [comment]
Works with Win10 and 8.1 ... I think you downloaded a broken file

**Comment by roque-canales** [comment]
No I downloaded it today at this adress.

**Comment by ghost** [comment]
I tested win8 at VMware and the config tool worked fine, so did the firmware update, reading parameters and saving parameters. Is the USB port recognized by the OS? If not, please refer to the px4 install driver.

**Comment by ghost** [comment]
This issue should caused by  Decimal symbol of region settings. 
http://en.playuav.com/question/7
The new CT has been released. Just closed and I am happy to re-open it if there is still has such issue.
